Add missing noexcept to declaration
system/libhwbinder/vts/performance/PerfTest.cpp:66:7: error: exception specification in declaration does not match previous declaration
Pipe::Pipe(Pipe&& rval) noexcept {
      ^
system/libhwbinder/vts/performance/PerfTest.h:37:5: note: previous declaration is here
    Pipe(Pipe&& rval);
    ^
1 error generated.

Bug: http://b/111067277
Test: Builds with C++17.
Change-Id: I6ff366835aa7328462c7f493754b01417109feee